### ISSUE TITLE
Error in config.json

### ISSUE THREAD

**Issue by Manlor** [Nibodhika/vtmv5-bot#9]
Hello,

Thank you for the bot. This is such a nice project!

I noticed an error in the config.json as suggested on the main page.

`{
 "token": "your token goes here",
 "tenets": [
    "First campaign tenet goes here",
    "Second campaign tenet goes here",
    "Third campaign tenet goes here",
    ]
}`

It gives an error (At least on ubuntu). There should not be a comma after the last line. it should read like this:

`{
 "token": "your token goes here",
 "tenets": [
    "First campaign tenet goes here",
    "Second campaign tenet goes here",
    "Third campaign tenet goes here"
    ]
}`

Thank you so much for your awesome work

**Comment by Nibodhika** [comment]
Hello, thanks for the feedback. You are correct, JSONs should not have a comma on the last element (oops, damn Python and its forgiving language).

I will fix it later today, but I have abandoned this project in favor of https://gitlab.com/Nibodhika/gmnotes which I haven't given a lot of attention lately because it needs a huge overhaul, and I have been busy (and lazy mostly) to get to it.

Reasons why you should migrate to it: 

* GMNotes allows for multiple campaigns, as well as different systems (although only V5 is currently implemented).

* It has a webUI that allows you to see and edit characters sheet more easily.

* One of the last things I implemented was the ability to play music or sounds on the discord channel.
